<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            
            [
                'name' => '<s>Crystal Meth</s> Blueberry Candy',
                'description' => "Crystallized perfection in every bite. Our signature Blueberry Candy isn't just sweet—it's dangerously delicious. ",
                'price' => 1200.00,
                'category' => 'edibles',
                'image' => 'bluemeth1.webp',
                'stock' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '<s>Ecstasy</s> Sour Chewables',
                'description' => 'Chewy, tangy, and a little wild.',
                'price' => 400.00,
                'category' => 'edibles',
                'image' => 'ecstacy.jpg',
                'stock' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '<s>Heroin</s> Powdered Sugar',
                'description' => 'Sweet, soft, and dangerously smooth.',
                'price' => 500.00,
                'category' => 'edibles',
                'image' => 'heroin.jpg',
                'stock' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '<s>Cocaine</s> Vanilla Powder',
                'description' => 'Classic vanilla with a kick.',
                'price' => 1000.00,
                'category' => 'edibles',
                'image' => 'cocaine.jpg',
                'stock' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '<s>Marijuana</s> Flavorful Herbs',
                'description' => 'Earthy, aromatic, and relaxing.',
                'price' => 600.00,
                'category' => 'edibles',
                'image' => 'cannabis.jpg',
                'stock' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '<s>Fentanyl</s> Funtanyls',
                'description' => 'Potent, tiny, and packs a punch.',
                'price' => 800.00,
                'category' => 'edibles',
                'image' => 'fent.jpg',
                'stock' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '<s>Hallucinogens</s> Magic Shrooms',
                'description' => 'Funky, earthy, and mind-bending.',
                'price' => 900.00,
                'category' => 'edibles',
                'image' => 'magicshrooms.jpg',
                'stock' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '<s>Liquid Ecstasy</s> Sweet Syrup',
                'description' => 'Smooth, sweet, and syrupy.',
                'price' => 700.00,
                'category' => 'edibles',
                'image' => 'liquidecstasy.webp',
                'stock' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '<s>Crack Cocaine</s> Polvoron',
                'description' => 'Crumbly, rich, and melts in your mouth.',
                'price' => 800.00,
                'category' => 'edibles',
                'image' => 'crack.jpg',
                'stock' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Toys
            [
                'name' => 'AK-47',
                'description' => 'Classic spring-loaded toy rifle. Durable and realistic.',
                'price' => 1500.00,
                'category' => 'toys',
                'image' => 'guns/ak47.jpg',
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Benelli M4',
                'description' => 'Pump-action fun for all ages.',
                'price' => 2000.00,
                'category' => 'toys',
                'image' => 'guns/benellim4.webp',
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beretta M9',
                'description' => 'Compact, lightweight, and safe for play.',
                'price' => 900.00,
                'category' => 'toys',
                'image' => 'guns/berettam9.jpg',
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Colt 1911',
                'description' => 'A timeless toy pistol for collectors and kids.',
                'price' => 850.00,
                'category' => 'toys',
                'image' => 'guns/colt1911.webp',
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FN Scar',
                'description' => 'Modern design, spring-loaded action.',
                'price' => 2100.00,
                'category' => 'toys',
                'image' => 'guns/fnscar.webp',
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Glock 17',
                'description' => 'Safe, reliable, and fun for roleplay.',
                'price' => 800.00,
                'category' => 'toys',
                'image' => 'guns/glock17.jpg',
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'M4 AR15',
                'description' => 'Tactical toy rifle with realistic details.',
                'price' => 2500.00,
                'category' => 'toys',
                'image' => 'guns/m4ar15.jpeg',
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mossberg 500',
                'description' => 'Pump-action shotgun replica for safe play.',
                'price' => 1700.00,
                'category' => 'toys',
                'image' => 'guns/mossberg500.jpg',
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Remington 870',
                'description' => 'Classic shotgun toy, sturdy and fun.',
                'price' => 1900.00,
                'category' => 'toys',
                'image' => 'guns/remington870.webp',
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Problem Solvers (Hitmen)
            [
                'name' => 'Jesse Pinkman',
                'description' => 'A loyal partner with a knack for chemistry.',
                'price' => 1400.00,
                'category' => 'problemsolvers',
                'image' => 'hitmen/jesse.webp',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eduardo Salamanca',
                'description' => 'A cunning strategist with a ruthless edge.',
                'price' => 3200.00,
                'category' => 'problemsolvers',
                'image' => 'hitmen/lalo.jpg',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mike Ehrmantraut',
                'description' => 'A former cop turned fixer with a heart of gold.',
                'price' => 3400.00,
                'category' => 'problemsolvers',
                'image' => 'hitmen/mike.jpg',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ignacio Varga',
                'description' => 'A resourceful and loyal enforcer.',
                'price' => 2400.00,
                'category' => 'problemsolvers',
                'image' => 'hitmen/nacho.jpg',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Salamanca Twins',
                'description' => 'A pair of deadly twins with a flair for chaos.',
                'price' => 2700.00,
                'category' => 'problemsolvers',
                'image' => 'hitmen/salamancatwins.webp',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Todd Alquist',
                'description' => 'A charming but dangerous enforcer.',
                'price' => 1100.00,
                'category' => 'problemsolvers',
                'image' => 'hitmen/todd.webp',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tuco Salamanca',
                'description' => 'A volatile and unpredictable enforcer.',
                'price' => 2500.00,
                'category' => 'problemsolvers',
                'image' => 'hitmen/tuco.jpg',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tyrus',
                'description' => 'A loyal and deadly enforcer.',
                'price' => 1700.00,
                'category' => 'problemsolvers',
                'image' => 'hitmen/tyrus.jpg',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Victor',
                'description' => 'A silent but deadly enforcer.',
                'price' => 2000.00,
                'category' => 'problemsolvers',
                'image' => 'hitmen/victor.jpg',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Legal Friends (Lawyers)
            [
                'name' => 'Chuck McGill',
                'description' => 'A brilliant lawyer with a complicated past.',
                'price' => 2300.00,
                'category' => 'legalfriends',
                'image' => 'lawyers/chuck.webp',
                'stock' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gustavo Fring',
                'description' => 'A meticulous and strategic lawyer.',
                'price' => 2200.00,
                'category' => 'legalfriends',
                'image' => 'lawyers/gus.webp',
                'stock' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Howard Hamlin',
                'description' => 'A charismatic and ambitious lawyer.',
                'price' => 2500.00,
                'category' => 'legalfriends',
                'image' => 'lawyers/howard.jpg',
                'stock' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kim Wexler',
                'description' => 'A dedicated and skilled lawyer.',
                'price' => 2500.00,
                'category' => 'legalfriends',
                'image' => 'lawyers/kim.jpg',
                'stock' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rich Schweikart',
                'description' => 'A savvy and experienced lawyer.',
                'price' => 1900.00,
                'category' => 'legalfriends',
                'image' => 'lawyers/rich.jpg',
                'stock' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Saul Goodman',
                'description' => 'A flamboyant and cunning lawyer.',
                'price' => 2600.00,
                'category' => 'legalfriends',
                'image' => 'lawyers/saulgoodman.jpg',
                'stock' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Add more products as needed
        ]);
    }
}
